### ISSUE TITLE
NativeLib repository not found

### ISSUE THREAD

**Issue by martinpelli** [DrMoriarty/nativelib#1]
Hi, I am trying to install push notification plugin, for that I need this plugin.

I have installed the plugin but when I press the NativeLib button on the top right, there is no plugin to search, I think I have to find the LOCAL-NOTIFICATION plugin there but there is nothing. Also,  I have an error that says nativelib repository not found and then installed addons/NativeLib/nativelib (34836 bytes)

I don’t have an idea of what means so I think maybe I have to install nativelib on my windows, but when searching on google I can’t find a link to downlod. Can someone guide me? I am very lost here

**Comment by DrMoriarty** [comment]
@martinpelli Could you show all text from godot's output view?
Also I need to know your OS version and godot version.

**Comment by DrMoriarty** [comment]
@martinpelli I added some additional checks in NativeLib addon. Also some error situations now shows more obvious. So update addon with new version.
And I updated README platform notes. Check it.

**Comment by martinpelli** [comment]
![image](https://user-images.githubusercontent.com/63437171/103291910-80060900-49cb-11eb-9240-bc30ff9f44b4.png)
 Thanks I updated but is not working for me. I have windows 10 64 bits, godot 3.2.3 stable and pyhton 3.9.1

**Comment by martinpelli** [comment]
@DrMoriarty in select python I have this 
![image](https://user-images.githubusercontent.com/63437171/103292209-23efb480-49cc-11eb-95d0-052ff87c07eb.png)

**Comment by DrMoriarty** [comment]
@martinpelli Looks like command line utility updated packages info, but addon can not find it. Could you check if folder `.nativelib` exist in your home directory? (it can be hidden by default)

**Comment by martinpelli** [comment]
> @martinpelli Looks like command line utility updated packages info, but addon can not find it. Could you check if folder `.nativelib` exist in your home directory? (it can be hidden by default)

Yes, in C:/users/myuser/.nativelib exists

**Comment by DrMoriarty** [comment]
@martinpelli I added path info to error log. Update addon and reopen your project. Than show me all output.

**Comment by martinpelli** [comment]
@DrMoriarty 
![image](https://user-images.githubusercontent.com/63437171/103294232-34099300-49d0-11eb-95cf-5c5709236211.png)

**Comment by DrMoriarty** [comment]
@martinpelli I committed one more change. Test it please.

**Comment by martinpelli** [comment]
> @martinpelli I committed one more change. Test it please.

![image](https://user-images.githubusercontent.com/63437171/103329720-d19aac00-4a3c-11eb-8f55-68b9e2753b67.png)

Workiing now, but I can´t see the button to install it, and have some errros on output. maybe is because of the path is not usr is users???

**Comment by DrMoriarty** [comment]
@martinpelli One more fix committed. I hope it will be enough to resolve the issue.

**Comment by martinpelli** [comment]
@DrMoriarty working now! thanks for your time dude!!
