### ISSUE TITLE
403 errors when accessing dl.bintray.com

### ISSUE THREAD

**Issue by nvoorhies** [DrMoriarty/nativelib#10]
Currently a number of nativelib modules appear to get a 403 forbidden error when attempting to download file(s) from dl.bintray.com.
It looks like dl.bintray.com has been sunset according to their front page. 
The particular error I ran into was as following:
Invoked via Nativelib addon or nativelib CLI using `nativelib -i applovinmax`

Failed while attempting to access https://dl.bintray.com/mobilap/nativelib/nativelib-export_0.1.0_all.tgz

Stack trace follows:

Traceback (most recent call last):
  File "addons/NativeLib/nativelib", line 1172, in <module>
    install_package(p, v)
  File "addons/NativeLib/nativelib", line 941, in install_package
    if not install_package(p, v):
  File "addons/NativeLib/nativelib", line 946, in install_package
    download_package(package_name, version, package_meta)
  File "addons/NativeLib/nativelib", line 436, in download_package
    path = download(f['url'], fname, home)
  File "addons/NativeLib/nativelib", line 411, in download
    (filepath, headers) = urlretrieve(url, os.path.join(path, filename), reporthook=_progress)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by DrMoriarty** [comment]
@nvoorhies Try to update the local repository info: `nativelib --update` or right bottom button in NativeLib view.
All plugins already republished to github.

**Comment by nvoorhies** [comment]
Confirmed that problems persists through --update of CLI.
Looking at https://github.com/godot-asset/index it appears that the .json still points to the bintray URLs rather than the published github releases.

Confirmed that manually changing the ~/.nativelib/meta/applovinmax/applovinmax_0.1.1_meta.json as follows resulted in successful installation 
```
15c15
<       "url": "https://dl.bintray.com/mobilap/nativelib/applovinmax_0.1.1_all.tgz"
---
>       "url": "https://github.com/DrMoriarty/godot-applovin-max/releases/download/v0.1.1/applovinmax_0.1.1_all.tgz"
24c24
<         "url": "https://dl.bintray.com/mobilap/nativelib/applovinmax_0.1.1_android.tgz"
---
>         "url": "https://github.com/DrMoriarty/godot-applovin-max/releases/download/v0.1.1/applovinmax_0.1.1_android.tgz"
30c30
<       "nativelib-export@0.1.0"
---
>       "nativelib-export@0.2.0"
35c35
<         "url": "https://dl.bintray.com/mobilap/nativelib/applovinmax_0.1.1_ios.tgz"
---
>         "url": "https://github.com/DrMoriarty/godot-applovin-max/releases/download/v0.1.1/applovinmax_0.1.1_ios.tgz"

```
It looks like following files in `godot-asset/index` have dangling links to bintray still
```
adcolony/adcolony_0.1.0_meta.json
adcolony/adcolony_0.2.0_meta.json
amplitude/amplitude_0.1.0_meta.json
applovin/applovin_0.1.0_meta.json
applovin/applovin_0.2.0_meta.json
applovinmax-facebook/applovinmax-facebook_0.1.0_meta.json
applovinmax-google/applovinmax-google_0.1.0_meta.json
appsflyer/appsflyer_0.2.1_meta.json
facebook/facebook_0.1.3_meta.json
facebook/facebook_0.1.4_meta.json
facebook/facebook_0.1.5_meta.json
facebook/facebook_0.1.6_meta.json
firebase-analytics/firebase-analytics_0.1.0_meta.json
firebase-auth/firebase-auth_0.1.0_meta.json
firebase-core/firebase-core_0.1.0_meta.json
firebase-crashlytics/firebase-crashlytics_0.1.0_meta.json
firebase-database/firebase-database_0.1.0_meta.json
firebase-performance/firebase-performance_0.1.0_meta.json
firebase-remoteconfig/firebase-remoteconfig_0.1.0_meta.json
firebase-remoteconfig/firebase-remoteconfig_0.1.1_meta.json
flurry/flurry_0.1.1_meta.json
googleplay-billing/googleplay-billing_1.0.1_meta.json
local-notification/local-notification_0.1.2_meta.json
local-notification/local-notification_0.1.3_meta.json
local-notification/local-notification_0.1.4_meta.json
local-notification/local-notification_0.1.5_meta.json
multidex/multidex_0.1.0_meta.json
nativelib-export/nativelib-export_0.1.0_meta.json
network/network_0.1.0_meta.json
ogury/ogury_0.1.1_meta.json
rateme/rateme_0.1.0_meta.json
tapdaq-adcolony/tapdaq-adcolony_0.1.0_meta.json
tapdaq-admob/tapdaq-admob_0.1.0_meta.json
tapdaq-applovin/tapdaq-applovin_0.1.0_meta.json
tapdaq-chartboost/tapdaq-chartboost_0.1.0_meta.json
tapdaq-fan/tapdaq-fan_0.1.0_meta.json
tapdaq-inmobi/tapdaq-inmobi_0.1.0_meta.json
tapdaq-ironsource/tapdaq-ironsource_0.1.0_meta.json
tapdaq-mintegral/tapdaq-mintegral_0.1.0_meta.json
tapdaq/tapdaq_0.1.0_meta.json
tapdaq-tapjoy/tapdaq-tapjoy_0.1.0_meta.json
tapdaq-unityads/tapdaq-unityads_0.1.0_meta.json
tapdaq-vungle/tapdaq-vungle_0.1.0_meta.json
tenjin/tenjin_0.1.0_meta.json
```

Closing and opening a separate issue on the godot-asset/index repository to update the bintray URLs to point at github releases.

Thanks for looking in to this!
