### ISSUE TITLE
Native Lib Not found

### ISSUE THREAD

**Issue by Octowyth** [DrMoriarty/nativelib#11]
Hi 

I'm creating a new games using godot 3.3.2 and install Nativelib from asset store, however I got this error after installing

![image](https://user-images.githubusercontent.com/80591569/123595323-f8367580-d81a-11eb-849b-1be559a131cc.png)

please advise if there's anything else I need to install for Godot 3.3.2

Thanks

**Comment by DrMoriarty** [comment]
Press the button "NativeLib-CLI" and show me the output of Godot. (the regular output view in the bottom where you usually see your game logs)

**Comment by Octowyth** [comment]
Sorry it was my mistake on the python path, should use it from C:\Users\<username>\AppData\Local rather than C:\Users\<username>\AppData\Roaming

All good now

Thanks

**Comment by Octowyth** [comment]
I Have a question on how I can update the plugin ?
I have other game that still use
