### ISSUE TITLE
NativeLib repository not found!

### ISSUE THREAD

**Issue by joncalderson** [DrMoriarty/nativelib#18]
Hi! thanks you in advance for your contribution with this plugin.

I follow all the steps but i reach always the same error.
First I download NativeLib from 'AssetLib' and after that i check the DrMoriarty plugin at Project -> Config --> Plugins.
Using Godot 3.5 Stable + Python 3.12 (tried other versions too).

But I obtain this error:
* modules/gdscript/gdscript_functions.cpp:775 - NativeLib repository not found! Search at C:\Users\jonca
/.nativelib/meta

 * modules/gdscript/gdscript_functions.cpp:775 - Try to update repository info (button "REPO")

![image](https://user-images.githubusercontent.com/34882099/212836801-88293f48-6870-4931-b8f3-94203b5415c8.png)
![image](https://user-images.githubusercontent.com/34882099/212836920-87e07a35-28c5-4f6a-9f29-d6327f5d35e5.png)

**Comment by GudsSonn** [comment]
Hi! I have exactly the same problem(

**Comment by GudsSonn** [comment]
Bro, I found a temporary solution!
Install as normal go to your addons folder > NativeLib > MainUI.gd and find the load_storage function and replace the path with a direct path to your meta folder as I have done in the image below. Not perfect but should get it running for now
![194624231-b11a3c41-a141-4353-ae8f-b3e16868ecbc](https://user-images.githubusercontent.com/122980787/213163934-5247ed7e-8d7b-4969-90a0-c0b15a49590f.png)

**Comment by joncalderson** [comment]
Great! thanks a lot @GudsSonn!
In my case was:
![image](https://user-images.githubusercontent.com/34882099/213773061-42175fbd-6f7f-4b7c-bd33-2cc9576f46ef.png)

Careful with de slash orientation!
