### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by tigurik** [DrMoriarty/nativelib#3]
**Steps to reproduce**
1. Go to AssetLib
2. Find and install NativeLib
3. Go to Project Settings and enable NativeLib
4. Go to the NativeLib tab
5. Set the path to Python.

**Result**:
NativeLib not found.

**Log**:
"No such file or directory: 'C: \\ Users \\ user \\. Nativelib \\ master.tar.gz'"

**Decision**:
Create .nativelib folder manually and press NativeLibCLI

**Comment by DrMoriarty** [comment]
@tigz19 Could you show me the full log of first start godot with addon?

**Comment by DrMoriarty** [comment]
@tigz19 Thank you for report! The issue was fixed in NativeLib-CLI v0.3.2
