### ISSUE TITLE
NativeLib not found

### ISSUE THREAD

**Issue by dpensky** [DrMoriarty/nativelib#6]
I believe there is a missing dependency not documented on the README.md

![image](https://user-images.githubusercontent.com/7250660/111792283-dbe17f00-88a2-11eb-92cc-155efdd0e837.png)

**Comment by DrMoriarty** [comment]
HI @dpensky !
Try to update you python to version 3.6. The python 3.5 don't have secrets module.

**Comment by dpensky** [comment]
Tks
