### ISSUE TITLE
FirebaseCloudMessaging module not found

### ISSUE THREAD

**Issue by martinpelli** [DrMoriarty/nativelib#7]
The plugin is not working now, I tested it before and worked and now it can´t found the module. I tested it on 32.3 stable and also in 3.2.4 betas

```
03-19 20:17:45.320  1378  1612 E godot   : **WARNING**: FirebaseCloudMessaging module not found!
03-19 20:17:45.320  1378  1612 E godot   :    At: modules/gdscript/gdscript_functions.cpp:817:call() - FirebaseCloudMessaging module not found!
```

**Comment by DrMoriarty** [comment]
It is strange because I didn't change the plugin.
Check if it properly installed into the project (green icon of platforms in plugin settings)
Check if it enabled on export page.
If nothing helped then send me your APK file.

**Comment by martinpelli** [comment]
@DrMoriarty My fault, I don’t know why but my custom build was desactivated, I don’t touch it so sorry 🙄 I am very used to having it always activated, that I checked everything 30 times less that.

**Comment by martinpelli** [comment]
@DrMoriarty 
Oh, now I'm starting to figure out what's going on.
At first it didn't work and I checked everything and didn't realize what was, because it had worked before.
Later I realized that the plugin did not appear directly in the export. If I go to Android/Plugins it is not installing the two files that were installed before, one I think was the .gdap
I have tried godot 3.2.3 and 3.2.4 and it doesn't install them, it installs the autoload and the messaging script but it doesn't give me the option to enable it, I don't know if I broke my whole project or what haha

**Comment by martinpelli** [comment]
@DrMoriarty where you able to get it working? I tried everything but the .gdap and .aar file are never installed on my android/plugins folder

**Comment by DrMoriarty** [comment]
I don't know what happened in your project.
Could you show me the output when you are installing this plugin?
This is what I get when install it:
```
Checking project dependencies: firebase-core@0.1.0
Installing firebase-core@0.1.0
  Unpack firebase-core_0.1.0_android.tgz
Installing firebase-cloud-messaging@0.1.1
  Unpack firebase-cloud-messaging_0.1.1_all.tgz
  Unpack firebase-cloud-messaging_0.1.1_android.tgz
```

**Comment by martinpelli** [comment]
@DrMoriarty I get this:
 Checking project dependencies: firebase-core@0.1.0
Installing firebase-core@0.1.0
Installing firebase-cloud-messaging@0.1.1
  Unpack firebase-cloud-messaging_0.1.1_all.tgz

But I think is not my project, I tried creating new projects on all godots, I mean I tried creating a new project on godot 3.2.3 on 3.2.4, on betas, etc..
And it´s always installing the messaging script and the autoload is setted, but the plugins folder is empty, I don´t have the possibility to check the firebase messaging plugin on export settings. Also I got the .gdap and .aar files from an old project, when was working, and putted them on android/plugins folder, checked the firebase cloud messaging option on export settings and when exporting it dosen´t show the google services error like before (I am not putting the google services on android/build to know if it´s throwing the error) and is not throwing it.

**Comment by DrMoriarty** [comment]
I don't see in your output the file `firebase-cloud-messaging_0.1.1_android.tgz` So you have no android native library.
Check if you enabled android platform on NativeLib view.

**Comment by martinpelli** [comment]
@DrMoriarty yes, it was that, cannot believe that I was stuck 2 weeks with that, I didn't click that button before, so that's why I didn't realize that it could be that. thanks, again.

**Comment by giaunguyen2176** [comment]
For anyone else who might having this issue with android, remember to enable this plugin in **Project -> Export -> Android -> Plugins**
